### ISSUE TITLE
Feat: [DMS] DMS 와 User Interface, FCA/LCA, DB 간 통신

### ISSUE THREAD

**Issue by jis0202** [66yurimi99/Z-ERO#15]
## Description  
운전자 영상 정보를 User Interface로, 운전자 상태 정보를 FCA/LCA, DB로 전송합니다
<br>

## Todo 
- #9 완료 후<br>
- [x] 운전자 영상 프레임을 User Interface로 전송하는 코드 작성
- #4 완료 후<br>
- [x] 운전자 상태 정보를 FCA/LCA와 DB로 전송하는 코드 작성

<br>

**Comment by 66yurimi99** [comment]
DB 접근을 위한 API 구현이 완료되었습니다.
호출 예시 참고 부탁드립니다 https://github.com/66yurimi99/Z-ERO/issues/4#issuecomment-1823735410
