### ISSUE TITLE
Feat: [UI] 컨트롤 시스템 구현

### ISSUE THREAD

**Issue by daron135** [66yurimi99/Z-ERO#23]
## Description  
DB flag를 버튼을 눌러서 제어
<br>

## Todo  
- [x] Click "Start" button, Set DB flag (system=1)
- [x] Click "Stop" button, Reset DB flag (system=0)
<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.

**Comment by 66yurimi99** [comment]
DB 접근을 위한 API 구현이 완료되었습니다.
호출 예시 참고 부탁드립니다 https://github.com/66yurimi99/Z-ERO/issues/4#issuecomment-1823735410
