### ISSUE TITLE
Feat: [Raspberry pi]  Direction Control based on Lane Detection

### ISSUE THREAD

**Issue by akaError404** [66yurimi99/Z-ERO#28]
## Description  
Motor control based on Lane Detection, so drive car automatically
<br>

## Todo  
- [ ] Motor control to straight driving
- [ ] Motor control to curve driving
<br>

**Comment by akaError404** [comment]
import cv2
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO_RP = 1
GPIO_Right = 2
GPIO_Left = 3

GPIO.setup(GPIO_RP, GPIO.OUT)  # IN1
GPIO.setup(GPIO_Right, GPIO.OUT)  # PwM_R
GPIO.setup(GPIO_Left, GPIO.OUT)  # PWM_L

left_wheel = GPIO.PWM(GPIO_Left, 50)
right_wheel = GPIO.PWM(GPIO_Right, 50)

#Get object distance from NY
def get_Object_state(obj):
    obj_state = None
    #Far
    if obj==3:
        obj_state = 1
    #little bit closer
    elif obj==2:
        obj_state = 0.5
    #very close
    elif obj==1:
        obj_state = 0
    return obj_state

#Get theta from YM
def get_Direction(theta):
    if theta> 30:
        state = "right"
    elif -30<theta<30:
        state = "straight"
    else:
        state = "left"
    return state, theta

def Cal_velocity(obj_state, state, theta,left_vel, right_vel):
    print(f"Current state: {state}")
    #cv2.putText(.....)
    if state=="straight":
        left_wheel.ChangeDutyCycle(left_vel*theta)
        right_wheel.ChangeDutyCycle(right_vel*theta)
    elif state=="right":
        left_wheel.ChangeDutyCycle(left_vel*theta)
        right_wheel.ChangeDutyCycle(0.3*right_vel*theta)
    elif state=="left":
        left_wheel.ChangeDutyCycle(0.3*left_vel * theta)
        right_wheel.ChangeDutyCycle(right_vel * theta)

if __name__ =="__main__":
    ##connection code
    #while to keep sending the video
    default_vel = 80
    #get from YS whether car is turned on
    if isCarOpened:
        left_wheel.start(0)
        right_wheel.start(0)
        if Driver_state>=1: #Driver is asleep
            obj_state = get_Object_state(obj)
            curr_state, curr_theta = get_Direction(theta)
            Cal_velocity(obj_state, curr_state, curr_theta, default_vel, default_vel)

Review my code structure plz

**Comment by daron135** [comment]
```python
def Cal_velocity(obj_state, state, theta,left_vel, right_vel):
    print(f"Current state: {state}")
    #cv2.putText(.....)
    if state=="straight":
        left_wheel.ChangeDutyCycle(left_vel*theta)
        right_wheel.ChangeDutyCycle(right_vel*theta)
    elif state=="right":
        left_wheel.ChangeDutyCycle(left_vel*theta)
        right_wheel.ChangeDutyCycle(0.3*right_vel*theta)
    elif state=="left":
        left_wheel.ChangeDutyCycle(0.3*left_vel * theta)
        right_wheel.ChangeDutyCycle(right_vel * theta)
```
obj_state를 Input 으로 받는데 obj_state 값에 따른 상태 변화가 없는것 같습니다.
이 부분만 추가해서 obj_state값에 따라 차량 제어 하면 좋을 것 같습니다.
나머지 알고리즘은 구현 방법 좋은것 같습니다.
